# Generated by Django 5.1 on 2024-08-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingrestaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='is_vagetarian',
            new_name='is_vegetarian',
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=15),
        ),
        migrations.AlterField(
            model_name='weddinghallprice',
            name='time',
            field=models.CharField(choices=[('Sáng', 'Sáng'), ('Trưa', 'Trưa'), ('Tối', 'Tối')], max_length=20),
        ),
    ]
