# Generated by Django 5.1 on 2024-08-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingrestaurant', '0002_rename_is_vagetarian_food_is_vegetarian_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weddingbooking',
            old_name='method',
            new_name='payment_method',
        ),
    ]
