# Generated by Django 5.1 on 2024-08-25 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingrestaurant', '0003_rename_method_weddingbooking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='wedding_booking',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='weddingrestaurant.weddingbooking'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Rất tệ'), (2, 'Tệ'), (3, 'Bình thường'), (4, 'Tốt'), (5, 'Rất tốt')]),
        ),
    ]
