# Generated by Django 5.1 on 2024-08-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingrestaurant', '0005_alter_feedback_wedding_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddinghallprice',
            name='is_holiday',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=15, null=True),
        ),
    ]
