# Generated by Django 5.1 on 2024-08-30 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingrestaurant', '0006_remove_weddinghallprice_is_holiday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingbooking',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='weddingrestaurant.customer'),
        ),
    ]
