# Generated by Django 5.1 on 2024-09-06 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingrestaurant', '0007_weddingbooking_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingbooking',
            name='wedding_hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddingrestaurant.weddinghall'),
        ),
        migrations.AlterField(
            model_name='weddingbooking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddingrestaurant.customer'),
        ),
    ]
