# Generated by Django 5.1 on 2024-09-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingrestaurant', '0008_weddingbooking_wedding_hall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingbooking',
            name='time_of_day',
            field=models.CharField(default='Sáng', max_length=20),
        ),
    ]
