# Generated by Django 5.1 on 2024-09-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingrestaurant', '0009_weddingbooking_time_of_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkbookingdetail',
            name='unit',
        ),
        migrations.AddField(
            model_name='drink',
            name='unit',
            field=models.CharField(default='Chai', max_length=50),
        ),
        migrations.AlterField(
            model_name='weddingbooking',
            name='time_of_day',
            field=models.CharField(max_length=20),
        ),
    ]
