# Generated by Django 5.1 on 2024-10-01 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingrestaurant', '0010_remove_drinkbookingdetail_unit_drink_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingbooking',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weddingrestaurant.staff'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
